# This is a basic workflow to help you get started with Actions
name: hola-mundo
run-name: ¡Aprendiendo Github Actions!

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ "aprendiendo-github-actions" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  hola-mundo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Clonar el repositorio en la máquina virtual
      - name: Checkout
        uses: actions/checkout@v3
      # Ejecutar hola mundo en Python!
      - name: Ejecutar Script
        run: python hola_mundo.py
